{
 "title": "Fuse Pool Details",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "poolID",
    "label": "Pool ID",
    "query": {
     "query": "label_values(fuse_pool_assets_supply_amount, id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pool Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_borrow_usd{id=\"$poolID\"}) / sum(fuse_pool_assets_supply_usd{id=\"$poolID\"})"
    }
   ]
  },
  {
   "title": "Pool USD Total Value Locked/Borrowed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_supply_usd{id=\"$poolID\"})",
     "legendFormat": "TVL"
    },
    {
     "expr": "sum(fuse_pool_assets_borrow_usd{id=\"$poolID\"})",
     "legendFormat": "TVB"
    }
   ]
  },
  {
   "title": "USD TVL Per Asset",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_pool_assets_supply_usd{id=\"$poolID\"}",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "USD TVB/TVL Per Asset",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "fuse_pool_assets_supply_usd{id=\"$poolID\"}",
     "legendFormat": "{{symbol}} TVL"
    },
    {
     "expr": "fuse_pool_assets_borrow_usd{id=\"$poolID\"}",
     "legendFormat": "{{symbol}} TVB"
    }
   ]
  },
  {
   "title": "Pool USD Total Supplied",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_supply_usd{id=\"$poolID\"})"
    }
   ]
  },
  {
   "title": "Liquidations Per Asset",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fuse_pool_assets_liquidations{id=\"$poolID\"}",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "User Leverage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fuse_userLeverage{id=\"$poolID\", level=\"at_risk\"}",
     "legendFormat": "At Risk"
    },
    {
     "expr": "fuse_userLeverage{id=\"$poolID\", level=\"liquidatable\"}",
     "legendFormat": "Liquidatable"
    }
   ]
  },
  {
   "title": "USD TVB Per Asset",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_pool_assets_borrow_usd{id=\"$poolID\"}",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Pool USD Total Borrowed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_borrow_usd{id=\"$poolID\"})"
    }
   ]
  },
  {
   "title": "Fees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_fees_usd{id=\"$poolID\"})"
    }
   ]
  },
  {
   "title": "Reserves",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_reserves_usd{id=\"$poolID\"})"
    }
   ]
  },
  {
   "title": "Interest Rates Per Asset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fuse_pool_assets_interest_rate{id=\"$poolID\"}",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Utilization Per Asset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "fuse_pool_assets_borrow_usd{id=\"$poolID\"} / fuse_pool_assets_supply_usd{id=\"$poolID\"}",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Amount TVB/TVL Per Asset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fuse_pool_assets_supply_amount{id=\"$poolID\"}",
     "legendFormat": "{{symbol}} TVL"
    },
    {
     "expr": "fuse_pool_assets_borrow_amount{id=\"$poolID\"}",
     "legendFormat": "{{symbol}} TVB"
    }
   ]
  },
  {
   "title": "Liquidations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fuse_pool_assets_liquidations{id=\"$poolID\"})"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_pool_rss{id=\"$poolID\"}"
    }
   ]
  }
 ]
}